version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: tcm-notes-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: tcm_notes
      MYSQL_USER: tcm_user
      MYSQL_PASSWORD: tcm_password
    ports:
      - "33306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - tcm-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p123456"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: tcm-notes-app
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/tcm_notes?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
      # 注意：容器内部连接使用默认3306端口，因为是在Docker网络内部通信
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      SERVER_PORT: 8082
      # SERVER_SERVLET_CONTEXT_PATH: /api
    networks:
      - tcm-network

networks:
  tcm-network:
    driver: bridge

volumes:
  mysql-data: